/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.meera.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Invheader service. Represents a row in the &quot;jqgrid_Invheader&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.meera.model.impl.InvheaderModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.meera.model.impl.InvheaderImpl}.
 * </p>
 *
 * @author meera
 * @see Invheader
 * @see com.meera.model.impl.InvheaderImpl
 * @see com.meera.model.impl.InvheaderModelImpl
 * @generated
 */
public interface InvheaderModel extends BaseModel<Invheader> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a invheader model instance should use the {@link Invheader} interface instead.
	 */

	/**
	 * Returns the primary key of this invheader.
	 *
	 * @return the primary key of this invheader
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this invheader.
	 *
	 * @param primaryKey the primary key of this invheader
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the inv ID of this invheader.
	 *
	 * @return the inv ID of this invheader
	 */
	public long getInvId();

	/**
	 * Sets the inv ID of this invheader.
	 *
	 * @param invId the inv ID of this invheader
	 */
	public void setInvId(long invId);

	/**
	 * Returns the name of this invheader.
	 *
	 * @return the name of this invheader
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this invheader.
	 *
	 * @param name the name of this invheader
	 */
	public void setName(String name);

	/**
	 * Returns the ammount of this invheader.
	 *
	 * @return the ammount of this invheader
	 */
	public long getAmmount();

	/**
	 * Sets the ammount of this invheader.
	 *
	 * @param ammount the ammount of this invheader
	 */
	public void setAmmount(long ammount);

	/**
	 * Returns the tax of this invheader.
	 *
	 * @return the tax of this invheader
	 */
	public long getTax();

	/**
	 * Sets the tax of this invheader.
	 *
	 * @param tax the tax of this invheader
	 */
	public void setTax(long tax);

	/**
	 * Returns the total of this invheader.
	 *
	 * @return the total of this invheader
	 */
	public long getTotal();

	/**
	 * Sets the total of this invheader.
	 *
	 * @param total the total of this invheader
	 */
	public void setTotal(long total);

	/**
	 * Returns the notes of this invheader.
	 *
	 * @return the notes of this invheader
	 */
	@AutoEscape
	public String getNotes();

	/**
	 * Sets the notes of this invheader.
	 *
	 * @param notes the notes of this invheader
	 */
	public void setNotes(String notes);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.meera.model.Invheader invheader);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.meera.model.Invheader> toCacheModel();

	@Override
	public com.meera.model.Invheader toEscapedModel();

	@Override
	public com.meera.model.Invheader toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}